version: '3'

services:
  lets-run-app:
    build: .
    ports:
      - "9001:9001"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: lets_run
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - ./db:/docker-entrypoint-initdb.d